/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosECondicoesRouteImport } from './routes/termos-e-condicoes'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as PoliticaDeSegurancaRouteImport } from './routes/politica-de-seguranca'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosSitesInstitucionaisRouteImport } from './routes/servicos.sites-institucionais'
import { Route as ServicosSistemasWebRouteImport } from './routes/servicos.sistemas-web'
import { Route as ServicosIntegracoesRouteImport } from './routes/servicos.integracoes'
import { Route as ServicosConsultoriaTechRouteImport } from './routes/servicos.consultoria-tech'
import { Route as ServicosAutomacoesComIaRouteImport } from './routes/servicos.automacoes-com-ia'

const TermosECondicoesRoute = TermosECondicoesRouteImport.update({
  id: '/termos-e-condicoes',
  path: '/termos-e-condicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeSegurancaRoute = PoliticaDeSegurancaRouteImport.update({
  id: '/politica-de-seguranca',
  path: '/politica-de-seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSitesInstitucionaisRoute =
  ServicosSitesInstitucionaisRouteImport.update({
    id: '/sites-institucionais',
    path: '/sites-institucionais',
    getParentRoute: () => ServicosRoute,
  } as any)
const ServicosSistemasWebRoute = ServicosSistemasWebRouteImport.update({
  id: '/sistemas-web',
  path: '/sistemas-web',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosIntegracoesRoute = ServicosIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosConsultoriaTechRoute = ServicosConsultoriaTechRouteImport.update({
  id: '/consultoria-tech',
  path: '/consultoria-tech',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosAutomacoesComIaRoute = ServicosAutomacoesComIaRouteImport.update({
  id: '/automacoes-com-ia',
  path: '/automacoes-com-ia',
  getParentRoute: () => ServicosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-seguranca': typeof PoliticaDeSegurancaRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/servicos/automacoes-com-ia': typeof ServicosAutomacoesComIaRoute
  '/servicos/consultoria-tech': typeof ServicosConsultoriaTechRoute
  '/servicos/integracoes': typeof ServicosIntegracoesRoute
  '/servicos/sistemas-web': typeof ServicosSistemasWebRoute
  '/servicos/sites-institucionais': typeof ServicosSitesInstitucionaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-seguranca': typeof PoliticaDeSegurancaRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/servicos/automacoes-com-ia': typeof ServicosAutomacoesComIaRoute
  '/servicos/consultoria-tech': typeof ServicosConsultoriaTechRoute
  '/servicos/integracoes': typeof ServicosIntegracoesRoute
  '/servicos/sistemas-web': typeof ServicosSistemasWebRoute
  '/servicos/sites-institucionais': typeof ServicosSitesInstitucionaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-seguranca': typeof PoliticaDeSegurancaRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/servicos/automacoes-com-ia': typeof ServicosAutomacoesComIaRoute
  '/servicos/consultoria-tech': typeof ServicosConsultoriaTechRoute
  '/servicos/integracoes': typeof ServicosIntegracoesRoute
  '/servicos/sistemas-web': typeof ServicosSistemasWebRoute
  '/servicos/sites-institucionais': typeof ServicosSitesInstitucionaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/politica-de-seguranca'
    | '/servicos'
    | '/termos-e-condicoes'
    | '/servicos/automacoes-com-ia'
    | '/servicos/consultoria-tech'
    | '/servicos/integracoes'
    | '/servicos/sistemas-web'
    | '/servicos/sites-institucionais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/politica-de-seguranca'
    | '/servicos'
    | '/termos-e-condicoes'
    | '/servicos/automacoes-com-ia'
    | '/servicos/consultoria-tech'
    | '/servicos/integracoes'
    | '/servicos/sistemas-web'
    | '/servicos/sites-institucionais'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/politica-de-seguranca'
    | '/servicos'
    | '/termos-e-condicoes'
    | '/servicos/automacoes-com-ia'
    | '/servicos/consultoria-tech'
    | '/servicos/integracoes'
    | '/servicos/sistemas-web'
    | '/servicos/sites-institucionais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PoliticaDeSegurancaRoute: typeof PoliticaDeSegurancaRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  TermosECondicoesRoute: typeof TermosECondicoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-e-condicoes': {
      id: '/termos-e-condicoes'
      path: '/termos-e-condicoes'
      fullPath: '/termos-e-condicoes'
      preLoaderRoute: typeof TermosECondicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-seguranca': {
      id: '/politica-de-seguranca'
      path: '/politica-de-seguranca'
      fullPath: '/politica-de-seguranca'
      preLoaderRoute: typeof PoliticaDeSegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/sites-institucionais': {
      id: '/servicos/sites-institucionais'
      path: '/sites-institucionais'
      fullPath: '/servicos/sites-institucionais'
      preLoaderRoute: typeof ServicosSitesInstitucionaisRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/sistemas-web': {
      id: '/servicos/sistemas-web'
      path: '/sistemas-web'
      fullPath: '/servicos/sistemas-web'
      preLoaderRoute: typeof ServicosSistemasWebRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/integracoes': {
      id: '/servicos/integracoes'
      path: '/integracoes'
      fullPath: '/servicos/integracoes'
      preLoaderRoute: typeof ServicosIntegracoesRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/consultoria-tech': {
      id: '/servicos/consultoria-tech'
      path: '/consultoria-tech'
      fullPath: '/servicos/consultoria-tech'
      preLoaderRoute: typeof ServicosConsultoriaTechRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/automacoes-com-ia': {
      id: '/servicos/automacoes-com-ia'
      path: '/automacoes-com-ia'
      fullPath: '/servicos/automacoes-com-ia'
      preLoaderRoute: typeof ServicosAutomacoesComIaRouteImport
      parentRoute: typeof ServicosRoute
    }
  }
}

interface ServicosRouteChildren {
  ServicosAutomacoesComIaRoute: typeof ServicosAutomacoesComIaRoute
  ServicosConsultoriaTechRoute: typeof ServicosConsultoriaTechRoute
  ServicosIntegracoesRoute: typeof ServicosIntegracoesRoute
  ServicosSistemasWebRoute: typeof ServicosSistemasWebRoute
  ServicosSitesInstitucionaisRoute: typeof ServicosSitesInstitucionaisRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosAutomacoesComIaRoute: ServicosAutomacoesComIaRoute,
  ServicosConsultoriaTechRoute: ServicosConsultoriaTechRoute,
  ServicosIntegracoesRoute: ServicosIntegracoesRoute,
  ServicosSistemasWebRoute: ServicosSistemasWebRoute,
  ServicosSitesInstitucionaisRoute: ServicosSitesInstitucionaisRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PoliticaDeSegurancaRoute: PoliticaDeSegurancaRoute,
  ServicosRoute: ServicosRouteWithChildren,
  TermosECondicoesRoute: TermosECondicoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
