/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosECondicoesRouteImport } from './routes/termos-e-condicoes'
import { Route as PoliticaDeSegurancaRouteImport } from './routes/politica-de-seguranca'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ServicosRouteRouteImport } from './routes/servicos/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosIndexRouteImport } from './routes/servicos/index'
import { Route as ServicosSitesInstitucionaisRouteImport } from './routes/servicos/sites-institucionais'
import { Route as ServicosSistemasWebRouteImport } from './routes/servicos/sistemas-web'
import { Route as ServicosIntegracoesRouteImport } from './routes/servicos/integracoes'
import { Route as ServicosConsultoriaTechRouteImport } from './routes/servicos/consultoria-tech'
import { Route as ServicosAutomacoesComIaRouteImport } from './routes/servicos/automacoes-com-ia'

const TermosECondicoesRoute = TermosECondicoesRouteImport.update({
  id: '/termos-e-condicoes',
  path: '/termos-e-condicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeSegurancaRoute = PoliticaDeSegurancaRouteImport.update({
  id: '/politica-de-seguranca',
  path: '/politica-de-seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRouteRoute = ServicosRouteRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosRouteRoute,
} as any)
const ServicosSitesInstitucionaisRoute =
  ServicosSitesInstitucionaisRouteImport.update({
    id: '/sites-institucionais',
    path: '/sites-institucionais',
    getParentRoute: () => ServicosRouteRoute,
  } as any)
const ServicosSistemasWebRoute = ServicosSistemasWebRouteImport.update({
  id: '/sistemas-web',
  path: '/sistemas-web',
  getParentRoute: () => ServicosRouteRoute,
} as any)
const ServicosIntegracoesRoute = ServicosIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => ServicosRouteRoute,
} as any)
const ServicosConsultoriaTechRoute = ServicosConsultoriaTechRouteImport.update({
  id: '/consultoria-tech',
  path: '/consultoria-tech',
  getParentRoute: () => ServicosRouteRoute,
} as any)
const ServicosAutomacoesComIaRoute = ServicosAutomacoesComIaRouteImport.update({
  id: '/automacoes-com-ia',
  path: '/automacoes-com-ia',
  getParentRoute: () => ServicosRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servicos': typeof ServicosRouteRouteWithChildren
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-seguranca': typeof PoliticaDeSegurancaRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/servicos/automacoes-com-ia': typeof ServicosAutomacoesComIaRoute
  '/servicos/consultoria-tech': typeof ServicosConsultoriaTechRoute
  '/servicos/integracoes': typeof ServicosIntegracoesRoute
  '/servicos/sistemas-web': typeof ServicosSistemasWebRoute
  '/servicos/sites-institucionais': typeof ServicosSitesInstitucionaisRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-seguranca': typeof PoliticaDeSegurancaRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/servicos/automacoes-com-ia': typeof ServicosAutomacoesComIaRoute
  '/servicos/consultoria-tech': typeof ServicosConsultoriaTechRoute
  '/servicos/integracoes': typeof ServicosIntegracoesRoute
  '/servicos/sistemas-web': typeof ServicosSistemasWebRoute
  '/servicos/sites-institucionais': typeof ServicosSitesInstitucionaisRoute
  '/servicos': typeof ServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/servicos': typeof ServicosRouteRouteWithChildren
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-seguranca': typeof PoliticaDeSegurancaRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/servicos/automacoes-com-ia': typeof ServicosAutomacoesComIaRoute
  '/servicos/consultoria-tech': typeof ServicosConsultoriaTechRoute
  '/servicos/integracoes': typeof ServicosIntegracoesRoute
  '/servicos/sistemas-web': typeof ServicosSistemasWebRoute
  '/servicos/sites-institucionais': typeof ServicosSitesInstitucionaisRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/servicos'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/politica-de-seguranca'
    | '/termos-e-condicoes'
    | '/servicos/automacoes-com-ia'
    | '/servicos/consultoria-tech'
    | '/servicos/integracoes'
    | '/servicos/sistemas-web'
    | '/servicos/sites-institucionais'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/politica-de-seguranca'
    | '/termos-e-condicoes'
    | '/servicos/automacoes-com-ia'
    | '/servicos/consultoria-tech'
    | '/servicos/integracoes'
    | '/servicos/sistemas-web'
    | '/servicos/sites-institucionais'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/servicos'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/politica-de-seguranca'
    | '/termos-e-condicoes'
    | '/servicos/automacoes-com-ia'
    | '/servicos/consultoria-tech'
    | '/servicos/integracoes'
    | '/servicos/sistemas-web'
    | '/servicos/sites-institucionais'
    | '/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicosRouteRoute: typeof ServicosRouteRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PoliticaDeSegurancaRoute: typeof PoliticaDeSegurancaRoute
  TermosECondicoesRoute: typeof TermosECondicoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-e-condicoes': {
      id: '/termos-e-condicoes'
      path: '/termos-e-condicoes'
      fullPath: '/termos-e-condicoes'
      preLoaderRoute: typeof TermosECondicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-seguranca': {
      id: '/politica-de-seguranca'
      path: '/politica-de-seguranca'
      fullPath: '/politica-de-seguranca'
      preLoaderRoute: typeof PoliticaDeSegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof ServicosRouteRoute
    }
    '/servicos/sites-institucionais': {
      id: '/servicos/sites-institucionais'
      path: '/sites-institucionais'
      fullPath: '/servicos/sites-institucionais'
      preLoaderRoute: typeof ServicosSitesInstitucionaisRouteImport
      parentRoute: typeof ServicosRouteRoute
    }
    '/servicos/sistemas-web': {
      id: '/servicos/sistemas-web'
      path: '/sistemas-web'
      fullPath: '/servicos/sistemas-web'
      preLoaderRoute: typeof ServicosSistemasWebRouteImport
      parentRoute: typeof ServicosRouteRoute
    }
    '/servicos/integracoes': {
      id: '/servicos/integracoes'
      path: '/integracoes'
      fullPath: '/servicos/integracoes'
      preLoaderRoute: typeof ServicosIntegracoesRouteImport
      parentRoute: typeof ServicosRouteRoute
    }
    '/servicos/consultoria-tech': {
      id: '/servicos/consultoria-tech'
      path: '/consultoria-tech'
      fullPath: '/servicos/consultoria-tech'
      preLoaderRoute: typeof ServicosConsultoriaTechRouteImport
      parentRoute: typeof ServicosRouteRoute
    }
    '/servicos/automacoes-com-ia': {
      id: '/servicos/automacoes-com-ia'
      path: '/automacoes-com-ia'
      fullPath: '/servicos/automacoes-com-ia'
      preLoaderRoute: typeof ServicosAutomacoesComIaRouteImport
      parentRoute: typeof ServicosRouteRoute
    }
  }
}

interface ServicosRouteRouteChildren {
  ServicosAutomacoesComIaRoute: typeof ServicosAutomacoesComIaRoute
  ServicosConsultoriaTechRoute: typeof ServicosConsultoriaTechRoute
  ServicosIntegracoesRoute: typeof ServicosIntegracoesRoute
  ServicosSistemasWebRoute: typeof ServicosSistemasWebRoute
  ServicosSitesInstitucionaisRoute: typeof ServicosSitesInstitucionaisRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

const ServicosRouteRouteChildren: ServicosRouteRouteChildren = {
  ServicosAutomacoesComIaRoute: ServicosAutomacoesComIaRoute,
  ServicosConsultoriaTechRoute: ServicosConsultoriaTechRoute,
  ServicosIntegracoesRoute: ServicosIntegracoesRoute,
  ServicosSistemasWebRoute: ServicosSistemasWebRoute,
  ServicosSitesInstitucionaisRoute: ServicosSitesInstitucionaisRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}

const ServicosRouteRouteWithChildren = ServicosRouteRoute._addFileChildren(
  ServicosRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicosRouteRoute: ServicosRouteRouteWithChildren,
  ContatoRoute: ContatoRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PoliticaDeSegurancaRoute: PoliticaDeSegurancaRoute,
  TermosECondicoesRoute: TermosECondicoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
